VIDEO_PATH = "penalti.mp4"
MODEL_PATH = "yolov8s.pt"

GOAL_WIDTH_METERS = 7.32
BALL_CLASS_ID = 32

CONF_THRESHOLD = 0.15
ROI_MARGIN = 300

START_THRESHOLD = 3
MIN_MOVEMENT_PX = 2
MAX_JUMP_PX = 80
SMOOTH_ALPHA = 0.7

MAX_PRED_FRAMES = 5